version: "3.9"
   
services:
  postgres:
    image: postgres:13.1
    volumes:
      - db:/var/lib/postgresql/data
    env_file: env/db.env

  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
        - static_volume:/code/static
        - media_volume:/code/media
    env_file: env/settings.env
    expose:
        - 8000
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
    db:
    static_volume:
    media_volume: