# Generated by Django 3.2.4 on 2021-08-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日'),
        ),
    ]
