# Generated by Django 3.2.4 on 2021-08-03 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_alter_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
